function DemoApp(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',ic='.cache.html',_='/',lb='//',Tb='080E5222C760CA76BF9CF23F7470D51D',Ub='11C412F09808A60EA2232D8935536A5D',Vb='1D8513C043304FBA3E1DA677C997F9D0',Wb='1E1E463941385B22B0EF33F82389DC7D',Xb='231E10BE73FE541AF79F024F0D77E32A',Yb='2C58DDC910CE1D1D50E6C90ABAA92BF5',Zb='4AE0D64756B30EABF43402978DC10E1A',$b='62410A13D78908F96822FF813069CAFA',_b='8F79047903316332B4E8736B36695B27',hc=':',pb='::',kc='<script defer="defer">DemoApp.onInjectionDone(\'DemoApp\')<\/script>',hb='<script id="',sb='=',$='?',ac='A7669CC02ABC993A56207DFCCC743111',bc='AA01C0AC696ABF2BB06EC738163DAC26',cc='BA2DF4BFDDCB8A03F7FF68A1BDA554F6',ub='Bad handler "',jc='DOMContentLoaded',Q='DemoApp',eb='DemoApp.nocache.js',ob='DemoApp::',dc='E294F2AECCF86DCA72B83357E0E1065E',ec='EFBFCDEC611A9973F4DA168F2B13146E',fc='F4D3DC055DBBFC8465C2F5C983FD6439',gc='F7EED755D3016B260655199B64EA5A46',jb='SCRIPT',gb='__gwt_marker_DemoApp',Db='android',Fb='android_tablet',kb='base',cb='baseUrl',T='begin',Lb='blackberry',S='bootstrap',bb='clear.cache.gif',rb='content',Mb='desktop',Y='end',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',Rb='hosted.html?DemoApp',yb='iframe',ab='img',Gb='ipad',Hb='ipad_retina',Ib='iphone',Jb='ipod',zb="javascript:''",Qb='loadExternalRefs',mb='meta',Cb='mgwt.os',Eb='mobile',Nb='mobile.user.agent',Ob='mobilesafari',Bb='moduleRequested',X='moduleStartup',nb='name',Pb='not_mobile',Ab='position:absolute;width:0;height:0;border:none',Kb='retina',db='script',Sb='selectingPermutation',R='startup',fb='undefined';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}DemoApp=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Db)!=-1){if(a.indexOf(Eb)!=-1){return Db}else{return Fb}}if(a.indexOf(Gb)!=-1){if(window.devicePixelRatio>=2){return Hb}return Gb}if(a.indexOf(Ib)!=-1||a.indexOf(Jb)!=-1){if(window.devicePixelRatio>=2){return Kb}return Ib}if(a.indexOf(Lb)!=-1){return Lb}return Mb}();return b}};v[Cb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};w[Nb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Ob:Pb};v[Nb]={mobilesafari:0,not_mobile:1};DemoApp.onScriptLoad=function(){if(I){r=true;C()}};DemoApp.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Qb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Rb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Sb});if(!B()){try{G([Mb,Pb],Tb);G([Hb,Pb],Ub);G([Kb,Ob],Vb);G([Lb,Pb],Wb);G([Gb,Pb],Xb);G([Db,Ob],Yb);G([Kb,Pb],Zb);G([Lb,Ob],$b);G([Fb,Ob],_b);G([Ib,Ob],ac);G([Gb,Ob],bc);G([Fb,Pb],cc);G([Ib,Pb],dc);G([Db,Pb],ec);G([Mb,Ob],fc);G([Hb,Ob],gc);K=x[H(Cb)][H(Nb)];var M=K.indexOf(hc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+ic}catch(a){return}}var N;function O(){if(!s){s=true;C();if(n.removeEventListener){n.removeEventListener(jc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(jc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Qb,millis:(new Date).getTime(),type:T});n.write(kc)}
DemoApp();